class Comment < ActiveRecord::Base
  # the belongs_to method was automatically generated by Rails
  # when we typed post:references via the command line. It 
  # already understands that there is a relationship between
  # comments and posts. belongs_to method is the opposite of
  # has_many methods in the Post model in that each comment 
  # only belongs to one post whereas every post has many 
  # related comments.
  belongs_to :post
end
